name: Mirror main branch

on:
  workflow_dispatch: # запускать только вручную

jobs:
  sync-main:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # вся история

      - name: Push main to target repo
        run: |
          git remote add mirror https://x-access-token:${{ secrets.TARGET_TOKEN }}@github.com/USERNAME/TARGET-REPO.git
          git push mirror main --force
