name: Supabase Migration & Functions Deploy

on:
  workflow_dispatch: # manual run only

jobs:
  supabase-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repo
      - name: Checkout source repo
        uses: actions/checkout@v4

      # 2. Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      # 3. Install Supabase CLI locally
      - name: Install Supabase CLI
        run: npm install supabase --save-dev

      # 4. Verify Supabase CLI
      - name: Verify Supabase CLI
        run: npx supabase --version

      # 5. Link Supabase project (creates .supabase/config.json)
      - name: Link Supabase project
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
        run: |
          npx supabase link --project-ref ${{ secrets.SUPABASE_PROJECT_REF }}

      # 6. Run migrations
      - name: Run Supabase migrations
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
        run: |
          echo "🚀 Running migrations..."
          npx supabase db push --debug
          echo "✅ Migrations complete"

      # 7. Deploy Edge Functions
      - name: Deploy Edge Functions
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
        run: |
          echo "🚀 Deploying Edge Functions..."
          npx supabase functions deploy generate-message --debug
          echo "✅ Edge Functions deployed"
