name: Sync Main to Prod Branch

on:
  workflow_dispatch: # Manual trigger
  push:
    branches: [main]
    paths-ignore:
      - '.github/**'
      - 'README.md'

jobs:
  sync-to-prod:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
      
      - name: Create or update prod branch
        run: |
          # Check if prod branch exists remotely
          if git ls-remote --heads origin prod | grep -q refs/heads/prod; then
            echo "📦 Prod branch exists, checking out..."
            git checkout prod
            git pull origin prod
          else
            echo "🆕 Creating new prod branch..."
            git checkout -b prod
          fi
          
          # Merge main into prod
          echo "🔄 Merging main into prod..."
          git merge origin/main --strategy-option=theirs --no-edit
          
          # Push prod branch
          echo "📤 Pushing prod branch..."
          git push origin prod
          
          echo "✅ Main branch successfully synced to prod"